EXPLAIN SELECT TITLE 
	FROM BOOKS;
    
EXPLAIN SELECT FIRSTNAME, LASTNAME
	FROM READERS  
    WHERE FIRSTNAME LIKE 'John';



CREATE INDEX BOOKIND ON BOOKS (TITLE);

CREATE INDEX READERIND ON READERS (FIRSTNAME, LASTNAME);



EXPLAIN SELECT TITLE 
	FROM BOOKS;
    
EXPLAIN SELECT FIRSTNAME, LASTNAME
	FROM READERS  
    WHERE FIRSTNAME LIKE 'John';