
ALTER TABLE BOOKS ADD BESTSELLER BOOLEAN DEFAULT FALSE;

DROP PROCEDURE IF EXISTS UpdateBestsellers;

DELIMITER $$

CREATE PROCEDURE UpdateBestsellers()
BEGIN
    DECLARE BOOKCOUNT, DAYS, RB_ID INT;
    DECLARE FINISHED INT DEFAULT 0;
    DECLARE ALL_BOOKS CURSOR FOR SELECT BOOK_ID FROM BOOKS;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FINISHED = 1;
    OPEN ALL_BOOKS;
    WHILE (FINISHED = 0) DO
    FETCH ALL_BOOKS INTO RB_ID;
    IF (FINISHED = 0) THEN
        SELECT COUNT(*) FROM RENTS
        WHERE BOOK_ID = RB_ID
        INTO BOOKCOUNT;

        SELECT DATEDIFF(MAX(RENT_DATE), MIN(RENT_DATE)) + 1 FROM RENTS
        WHERE BOOK_ID = RB_ID
        INTO DAYS;

        UPDATE BOOKS SET BESTSELLER = TRUE
        WHERE BOOK_ID = RB_ID AND BOOKCOUNT > 2 AND DAYS BETWEEN 1 AND 30;
        COMMIT;
    END IF;
        END WHILE;

    CLOSE ALL_BOOKS;

    select * from BOOKS;

END $$

DELIMITER ;

CALL UpdateBestsellers();
